services:
  fastapi:
    build: ./app
    container_name: eveesi
#    ports:
#      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
    networks:
      - prom
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: eveesi_redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped
    networks:
      - prom

networks:
  prom:
    external: true
    name: secmon
